// Array of financial tips
export const financialTips = [
  {
    id: 1,
    title: "Emergency Fund Basics",
    description: "Aim to save 3-6 months of expenses in an emergency fund before focusing on other financial goals.",
    category: "Savings",
    icon: "💰",
  },
  {
    id: 2,
    title: "50/30/20 Rule",
    description: "Try allocating 50% of income to needs, 30% to wants, and 20% to savings and debt repayment.",
    category: "Budgeting",
    icon: "📊",
  },
  {
    id: 3,
    title: "Debt Snowball Method",
    description: "Pay minimum on all debts, then put extra money toward your smallest debt. Once paid off, roll that payment to the next smallest.",
    category: "Debt Management",
    icon: "❄️",
  },
  {
    id: 4,
    title: "Pay Yourself First",
    description: "Set up automatic transfers to your savings account on payday before spending on anything else.",
    category: "Savings",
    icon: "🏦",
  },
  {
    id: 5,
    title: "Avoid Impulse Purchases",
    description: "Follow the 24-hour rule: wait a day before making non-essential purchases to reduce impulse buying.",
    category: "Spending",
    icon: "🛍️",
  },
  {
    id: 6,
    title: "Track Your Expenses",
    description: "Record all expenses for at least 30 days to identify spending patterns and areas for improvement.",
    category: "Budgeting",
    icon: "📝",
  },
  {
    id: 7,
    title: "Power of Compound Interest",
    description: "Starting to save early, even small amounts, can lead to significant growth over time through compound interest.",
    category: "Investing",
    icon: "📈",
  },
  {
    id: 8,
    title: "Negotiate Bills",
    description: "Regularly review and negotiate recurring bills like insurance, internet, and phone services to lower monthly expenses.",
    category: "Cost Cutting",
    icon: "📞",
  },
  {
    id: 9,
    title: "Avoid Bank Fees",
    description: "Choose accounts without monthly fees and maintain minimum balances to avoid unnecessary charges.",
    category: "Banking",
    icon: "🏦",
  },
  {
    id: 10,
    title: "Financial Calendar",
    description: "Create a calendar with all bill due dates to avoid late fees and plan your cash flow better.",
    category: "Organization",
    icon: "📅",
  },
  {
    id: 11,
    title: "Use the 72 Rule",
    description: "Divide 72 by your interest rate to estimate how many years it will take for your money to double.",
    category: "Investing",
    icon: "🧮",
  },
  {
    id: 12,
    title: "Automate Your Finances",
    description: "Set up automatic bill payments and savings transfers to ensure you never miss a payment and consistently save.",
    category: "Organization",
    icon: "⚙️",
  },
  {
    id: 13,
    title: "Cook at Home",
    description: "Save money by preparing meals at home instead of eating out. Plan your meals weekly to optimize grocery shopping.",
    category: "Cost Cutting",
    icon: "🍳",
  },
  {
    id: 14,
    title: "Review Your Subscriptions",
    description: "Regularly audit your subscriptions and cancel those you don't use often to prevent wasting money on unused services.",
    category: "Spending",
    icon: "📱",
  },
  {
    id: 15,
    title: "Income Diversification",
    description: "Develop multiple income streams to increase financial stability and accelerate wealth building.",
    category: "Income",
    icon: "💼",
  },
  {
    id: 16,
    title: "Zero-Based Budgeting",
    description: "Assign a purpose to every dollar of income, ensuring your income minus expenses equals zero.",
    category: "Budgeting",
    icon: "0️⃣",
  },
  {
    id: 17,
    title: "Pay Bills on Time",
    description: "Avoid late fees and protect your credit score by paying all bills by their due dates.",
    category: "Credit",
    icon: "⏰",
  },
  {
    id: 18,
    title: "Use Cash Envelopes",
    description: "For problem spending areas, use physical cash in labeled envelopes to help stick to your budget limits.",
    category: "Spending",
    icon: "✉️",
  },
  {
    id: 19,
    title: "Review Insurance Policies",
    description: "Annually review all insurance policies to ensure adequate coverage at competitive rates.",
    category: "Insurance",
    icon: "🛡️",
  },
  {
    id: 20,
    title: "Save Windfalls",
    description: "When you receive unexpected money (tax refunds, bonuses, gifts), save at least 50% before spending any.",
    category: "Savings",
    icon: "🎁",
  }
];